# Generated by Django 4.1.1 on 2023-09-07 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_attendee_events'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendee',
            name='events',
        ),
    ]
