# Generated by Django 4.1.1 on 2023-10-21 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
