# Generated by Django 4.1.1 on 2023-10-25 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_schedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='event',
        ),
        migrations.AddField(
            model_name='event',
            name='schedules',
            field=models.ManyToManyField(blank=True, related_name='events_scheduled', to='api.schedule'),
        ),
    ]
