# Generated by Django 4.1.1 on 2023-10-26 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_schedule_event_event_schedules'),
    ]

    operations = [
        migrations.RenameField(
            model_name='speaker',
            old_name='name',
            new_name='fullname',
        ),
        migrations.RemoveField(
            model_name='speaker',
            name='bio',
        ),
        migrations.AddField(
            model_name='speaker',
            name='organization',
            field=models.CharField(default='Adama Science and Technology University', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='speaker',
            name='role',
            field=models.CharField(default='Associate Dean', max_length=255),
            preserve_default=False,
        ),
    ]
