# Generated by Django 4.1.1 on 2023-10-26 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_rename_name_speaker_fullname_remove_speaker_bio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='speakers',
        ),
        migrations.AddField(
            model_name='speaker',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='speakers', to='api.event'),
        ),
    ]
