# Generated by Django 4.1.1 on 2023-10-26 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_event_speakers_speaker_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='speaker',
            name='event',
        ),
        migrations.AddField(
            model_name='event',
            name='speakers',
            field=models.ManyToManyField(blank=True, related_name='events_speaking', to='api.speaker'),
        ),
    ]
