# Generated by Django 4.1.1 on 2023-10-27 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_speaker_event_event_speakers'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_status',
            field=models.CharField(default='upcoming', max_length=100),
            preserve_default=False,
        ),
    ]
