# Generated by Django 4.1.1 on 2023-10-27 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_appuser_is_admin_appuser_is_staff'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AppUser',
        ),
    ]
