# Generated by Django 4.1.1 on 2023-10-30 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_remove_event_event_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='activity',
            field=models.TextField(),
        ),
    ]
