# Generated by Django 5.0.1 on 2024-03-27 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_remove_event_event_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='event_attendee', to='api.event'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedule',
            name='event',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='event_schedules', to='api.event'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='speaker',
            name='event',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='event_speakers', to='api.event'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sponsor',
            name='event',
            field=models.ForeignKey(default='2', on_delete=django.db.models.deletion.CASCADE, related_name='event_sponsors', to='api.event'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='schedule',
            name='activity',
            field=models.TextField(),
        ),
    ]
