# Generated by Django 5.0.1 on 2024-03-31 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_attendee_event_schedule_event_speaker_event_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='speaker',
            name='event',
        ),
    ]
