# Generated by Django 5.0.1 on 2024-03-31 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_remove_speaker_event'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendee',
            old_name='event',
            new_name='the_event',
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='event',
            new_name='the_event',
        ),
        migrations.RenameField(
            model_name='sponsor',
            old_name='event',
            new_name='the_event',
        ),
        migrations.AddField(
            model_name='speaker',
            name='the_event',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='event_speakers', to='api.event'),
            preserve_default=False,
        ),
    ]
