# Generated by Django 5.0.1 on 2024-03-31 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_rename_event_attendee_the_event_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendee',
            name='the_event',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='the_event',
        ),
        migrations.RemoveField(
            model_name='speaker',
            name='the_event',
        ),
        migrations.RemoveField(
            model_name='sponsor',
            name='the_event',
        ),
    ]
