# Generated by Django 5.0.1 on 2024-04-19 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_eventuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomId', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='roomid',
            field=models.ManyToManyField(blank=True, related_name='events_roomid', to='api.roomid'),
        ),
    ]
